In [68]:
import requests
import pandas as pd

url = ("https://api.census.gov/data/2024/acs/acs5?get=group(B20004)&for=state:*")

response = requests.get(url)
data = response.json()

df = pd.DataFrame(data[1:],columns=data[0])

In [69]:
## drop all margin of error columns and additional columns created by API with NONE as output
df.columns = df.columns.astype(str)
df = df[[col for col in df.columns if not (col.endswith('M') or col.endswith('A'))]]

In [70]:
## keep only 6 first columns since rest are split by gender
df = df.iloc[:, :6]

In [71]:
## rename columns 
df.columns = [
    "Total",
    "Less than high school graduate",
    "High school graduate",
    "Some college or associate's degree",
    "Bachelor's degree",
    "Graduate or professional degree"
]

In [72]:
## index dataframe by states
states = [
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 
    'Delaware','District of Coluumbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 
    'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 
    'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 
    'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 
    'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 
    'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 
    'Wisconsin', 'Wyoming', 'Puerto Rico'
]
df.index = states

In [73]:
## remove Columbia and Puerto Rico since not official states
df = df.drop(['District of Columbia', 'Puerto Rico'], errors='ignore')

In [74]:
## Dataframe for earnings vs education by State
Earnings_By_State = df

In [75]:
## Save as CSV file
Earnings_By_State.to_csv("Earnings_By_State.csv", index=True)

In [76]:
Earnings_By_State

,Total,Less than high school graduate,High school graduate,Some college or associate's degree,Bachelor's degree,Graduate or professional degree
Alabama,46831,30696,37156,43231,61115,75030
Alaska,58591,35441,44678,54961,71035,92382
Arizona,51402,34212,40874,47651,67417,84105
Arkansas,44499,31882,36880,41256,57697,74020
California,56395,32480,41382,50157,80933,111188
Colorado,60455,37820,45140,50210,73999,90992
Connecticut,61786,34099,44726,51238,79601,99061
Delaware,53037,35002,40675,47864,68176,87287
District of Coluumbia,91950,33683,39810,50606,95471,123909
Florida,46867,30508,36593,43852,59953,78498
Georgia,50458,32349,37841,44633,67868,84480
Hawaii,53390,32827,43141,49303,63172,84680
Idaho,47428,35526,39186,43363,58289,79351
Illinois,55582,34655,40965,47813,73326,91623
Indiana,49693,34287,40411,47119,62429,79544
Iowa,51106,35996,41528,47635,62744,80022
Kansas,50504,35231,39282,45261,63396,75635
Kentucky,46524,29659,37177,43534,60526,70952
Louisiana,46510,29714,36782,42528,60472,70058
Maine,50103,35887,40775,46697,59190,75851
Maryland,65293,35487,45113,54823,80465,105640
Massachusetts,66782,36200,46175,52923,81726,102561
Michigan,50316,31851,37777,44844,66893,85195
Minnesota,58615,36257,42951,51845,73301,89644
Mississippi,42912,29259,35321,40529,53681,65353
Missouri,49030,32024,38607,44914,61818,75454
Montana,46951,33639,38073,42611,55623,72265
Nebraska,51569,37277,40830,47062,62298,78244
Nevada,47861,35906,40410,46240,62137,83858
New Hampshire,60332,40457,48323,52211,72069,88483
New Jersey,63226,33651,42773,51787,81924,105179
New Mexico,44666,28539,35325,41339,56443,78282
New York,57966,31511,40549,49306,76052,95435
North Carolina,49275,31234,37346,43525,64395,80986
North Dakota,52900,40757,43691,50379,60962,74877
Ohio,50614,32025,39940,45998,66950,84072
Oklahoma,46101,31734,37211,43445,58520,73412
Oregon,52362,35087,40655,46990,67899,88165
Pennsylvania,53549,33591,40643,47736,69335,87132
Rhode Island,57032,35368,44395,50876,70290,91744
South Carolina,47658,30223,37196,44160,61860,73671
South Dakota,49402,33790,40544,47061,58363,72377
Tennessee,48058,31689,38347,44566,61810,76817
Texas,51033,30970,37956,46890,70006,87663
Utah,54148,38971,43090,48162,65293,94608
Vermont,52923,37572,44691,46818,59469,75457
Virginia,59471,33905,41243,49185,76425,102924
Washington,62378,37363,46550,53700,81898,108295
West Virginia,45862,28863,37352,42135,57259,71098
Wisconsin,53060,36585,42367,49438,66239,79916
Wyoming,50636,38055,42107,45574,59382,74861

In [95]:
## create new dataframe for county: 

url = "https://api.census.gov/data/2024/acs/acs5?get=group(B20004)&for=county:*&in=state:*"
response = requests.get(url)
data = response.json()
df_county = pd.DataFrame(data[1:], columns=data[0])

In [96]:
## get rid of all margin of error and additional columns

df_county.columns = df_county.columns.astype(str)
df_county = df_county[[col for col in df_county.columns if not (col.endswith('M') or col.endswith('A'))]]

In [ ]:
## index rows by county NAME column

county_col = df_county.columns[-3]
df_county = df_county.set_index(county_col)

In [100]:
## keep only first six columns
df_county = df_county.iloc[:, :6]

In [99]:
## rename columns 

df_county.columns = [
    "Total",
    "Less than high school graduate",
    "High school graduate",
    "Some college or associate's degree",
    "Bachelor's degree",
    "Graduate or professional degree"
]

In [101]:
## remove all counties in Puerto Rico and Columbia

df_county = df_county[~df_county.index.str.endswith(("Puerto Rico", "Columbia"))]

In [107]:
## remove all counties which have negative or missing values 
df_county = df_county.apply(pd.to_numeric, errors='coerce')
df_county = df_county.dropna()
df_county = df_county[(df_county >= 0).all(axis=1)]

In [109]:
df_county

,Total,Less than high school graduate,High school graduate,Some college or associate's degree,Bachelor's degree,Graduate or professional degree
NAME,,,,,,
"Autauga County, Alabama",49028,40873,36261,47554,61673,88884
"Baldwin County, Alabama",50280,35339,41214,43700,66858,76200
"Barbour County, Alabama",35453,30551,32988,40000,48125,49349
"Bibb County, Alabama",36898,24073,31602,40480,48089,56500
"Blount County, Alabama",45785,33292,37479,49488,54912,75918
...,...,...,...,...,...,...
"Sublette County, Wyoming",55058,65750,32424,47132,66032,72296
"Sweetwater County, Wyoming",52763,31232,41385,52065,62591,78750
"Teton County, Wyoming",58405,41905,50152,55602,58857,95453
"Uinta County, Wyoming",47777,26806,41544,41110,66651,82292
"Washakie County, Wyoming",47590,54016,38275,44063,61393,80208

In [ ]:
Earnings_By_county.to_csv("Earnings_By_State.csv", index=True)